### ISSUE TITLE
[NEW][TABLE] playlist

### ISSUE THREAD

**Issue by Studyvelopers** [Studyvelopers/OverTheFlow-db#1]
### TABLE NAME
playlist

### TABLE DESCRIPTION
재생목록 정보를 가지는 테이블입니다.

### TABLE SCHEMA

NAME | TYPE | CONSTRAINTS
-- | -- | --
playlist_id | VARCHAR(255) | PK, NOT NULL
playlist_title | VARCHAR(255) | NOT NULL
playlist_description | TEXT | NOT NULL
playlist_register_date | DATETIME | NOT NULL
playlist_visibility_flag | BOOL | NOT NULL
member_id | VARCHAR(255) | FK, NOT NULL

### TABLE REFERENCES
- member

### TASK LISTS
- [x] 테이블 DDL 작성
- [x] 샘플 데이터 추가
- [x] 테이블 테스트

**Comment by dhjeon1993** [comment]
작업 완료
#14
