### ISSUE TITLE
[NEW][TABLE]member_likes_music

### ISSUE THREAD

**Issue by LJG070** [Studyvelopers/OverTheFlow-db#8]
### TABLE NAME
member_likes_music

### TABLE DESCRIPTION
각각의 회원들이 음악정보에 좋아요 적용 여부를 저장

### TABLE SCHEMA
NAME | TYPE | CONSTRAINTS
-- | -- | --
member_id | VARCHAR(255) | PFK
music_id | VARCHAR(255) | PFK

### TABLE REFERENCES
- music
- member

### TASK LISTS
- [x] 기본 DDL 작성
- [x] 샘플 데이터 추가
- [x] 테이블 단위 테스트

### BRANCH
#5, #9

**Comment by dhjeon1993** [comment]
@LJG070 
테이블 이름을 문법에 맞게 'member_likes_music'으로 하는건 어떤가요?

**Comment by LJG070** [comment]
수정하겠습니다
